package com.example.loginpage

import android.content.SharedPreferences
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.TextView
import com.example.loginpage.databinding.ActivityWelcomeBinding

class welcome_activity : AppCompatActivity() {
    // viewBinding
    // First need to enable feature in Gradel
    //AutoGenerated binding class that holdes the rfresrance to your XMl
    // XML - <tag1> <tag2> tag3>
    // inflate class to connect to our connect to our koptline file

    // TODO 1 : benefit of Jetpake viewBinding over normal View binding




    private  lateinit var  binding: ActivityWelcomeBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
       // setContentView(R.layout.activity_welcome)
        binding = ActivityWelcomeBinding.inflate(layoutInflater)
        setContentView(binding.root)

   //     val tvwelcome:TextView = findViewById(R.id.tvWelcomePage)

//        // fatch the maniAcitivity and display it here
//         val username =  intent.getStringExtra(USERNMAE_KEY)
//        val passWord = intent.getStringExtra(PASSWORD_KEY)
        val username =    intent.extras?.getString(USERNMAE_KEY)
        val passWord = intent.extras?.getString(PASSWORD_KEY)

     //   tvwelcome.text = "Welcome to my app $username \n$passWord"
        binding.tvWelcomePage.text = "Welcome to my app $username \\n$passWord"

        // 2. SharedPreferance
        /*
        is basically storing all your data in the file that is only accessiable to One app

         */
        val contanctNum = "7815081125"
        val isAdmin = true
        val ageOfUser = 20
        val SharedPrefs = SharedPreferences


    }

}