package com.example.loginpage

import android.content.Context
import android.content.SharedPreferences
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.widget.TextView
import com.example.loginpage.databinding.ActivityWelcomeBinding

class welcome_activity : AppCompatActivity() {
    // TODO viewBinding
    // First need to enable feature in Gradel
    //AutoGenerated binding class that holdes the rfresrance to your XMl
    // XML - <tag1> <tag2> tag3>.xml
    // tag1 tag2 tag3 Autogenerated class

    // inflate class to connect to our connect to our koptline file

    // TODO 1 : benefit of Jetpake viewBinding over normal View binding




    private  lateinit var  binding: ActivityWelcomeBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
       // setContentView(R.layout.activity_welcome)
        binding = ActivityWelcomeBinding.inflate(layoutInflater)
        setContentView(binding.root)

   //     val tvwelcome:TextView = findViewById(R.id.tvWelcomePage)

//        // fatch the maniAcitivity and display it here
//         val username =  intent.getStringExtra(USERNMAE_KEY)
//        val passWord = intent.getStringExtra(PASSWORD_KEY)
        val username =    intent.extras?.getString(USERNMAE_KEY)
        val passWord = intent.extras?.getString(PASSWORD_KEY)

     //   tvwelcome.text = "Welcome to my app $username \n$passWord"
        binding.tvWelcomePage.text = "Welcome to my app $username \\n$passWord"

        // 2. SharedPreferance
        /*
        is basically storing all your data in the file that is only accessiable to One app

         */
        // How to put the data in the Shared perfes
        val contanctNum = "7815081125"
        val isAdmin = true
        val ageOfUser = 20
        val SharedPrefs = getSharedPreferences(SHARED_PREF_FILE_NAME, Context.MODE_PRIVATE)
        val editor = SharedPrefs.edit()

        editor.putString(SP_CONTANCT_NUMBER_KEY , contanctNum)
        editor.putString(SP_IS_ADMIN_KEY ,isAdmin.toString())
        editor.putString(SP_AGE_KEY , ageOfUser.toString())

        editor.apply() // push the values in the Async Manner
      //  editor.commit() puch the value in the Sync manner
        // it will  Stop too much time while  puch the data


       // How to Acess the data from the SharedPref
        //

        val sharedPreferences = getSharedPreferences(SHARED_PREF_FILE_NAME , Context.MODE_PRIVATE)
        // mode private MUst be used in the case of SharedPreferance
       val cNum =  sharedPreferences.getString(SP_CONTANCT_NUMBER_KEY,"no number found ")
        val isadmin = sharedPreferences.getString(SP_IS_ADMIN_KEY , false.toString())
        val age = sharedPreferences.getInt(SP_AGE_KEY , 0)
        val name = sharedPreferences.getString("nameKey" , "no name found ")

        Log.d("SharedPreferanceTestTag" , "$cNum , $isadmin ,$age ,$name "  )






    }



    }

